/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.sql.Time;
import java.util.*;

public class App {
    public static void main(String[] args) {

        System.out.println("Running Train Booking App");
        Scanner sc = new Scanner(System.in);

        int option = 0;
        UserBookingService userBookingService;

        try{
            userBookingService = new UserBookingService();
        }catch(IOException ex){
            System.out.println("There is something wrong");
            return;
        }

        while(option != 7){
            System.out.print("Choose an option: ");
            System.out.println("1 For Sign Up");
            System.out.println("2 For Login");
            System.out.println("3 For Fetch Booking Details");
            System.out.println("4 For Search Trains");
            System.out.println("5 For Book a Seat");
            System.out.println("6 For Cancel my Booking");
            System.out.println("7 For Exit App");
            option = sc.nextInt();
            Train trainSelectedForBooking = new Train();
            switch (option){
                case 1:
                    System.out.println("Enter Your Username For Sign Up: ");
                    String nameToSignUp = sc.next();
                    System.out.println("Enter Your Password For Sign Up: ");
                    String passwordToSignUp = sc.next();
                    User userToSignUp = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter Your Username For Login: ");
                    String nameToLogin = sc.next();
                    System.out.println("Enter Your Password For Login: ");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin,passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin),new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    }catch (IOException e){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching Your Booking ");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String sourceStation = sc.next();
                    System.out.println("Type your destination station");
                    String destinationStation = sc.next();
                    List<Train> trains = userBookingService.getTrains(sourceStation,destinationStation);
                    int index = 1;
                    for(Train t : trains){
                        System.out.println(index+"Train id: "+ t.getTrainId());
                        for(Map.Entry<String, Time> entry: t.getStationTimes().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+ entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    trainSelectedForBooking = trains.get(sc.nextInt());
                    break;
                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row: seats){
                        for (Integer val: row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = sc.nextInt();
                    System.out.println("Enter the column");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;

                case 6:
                    System.out.println("Enter your ticket id to cancel booking");
                    String ticketId = sc.next();
                    Boolean canceled = userBookingService.cancelBooking(ticketId);
                    if(canceled.equals(Boolean.TRUE)){
                        System.out.println("Booking canceled successfully");
                    }else{
                        System.out.println("Couldn't cancel your booking");
                    }
                    break;
                default:
                    break;
            }
        }
    }
}
